# Generated by Django 3.2 on 2021-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.CharField(default='Bio Here', max_length=150),
        ),
    ]
